[package]
name = "copytree"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
arboard = "3.2"
clap = { version = "4.4", features = ["derive", "env"] }
ignore = "0.4"
globset = "0.4"
dotenvy = "0.15"
